# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Master Piece
author: Julien Bonnefoy
logo: ../../static/img/orange_300.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 120

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/julien-bonnefoy/website # Online location of your book
  path_to_book: website/orange/book  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true

# thebe
launch_buttons:
  thebe: true

# plotly
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

parse:
  myst_extended_syntax: true

only_build_toc_files: true